# Allow .htaccess (rewrite, etc.) in document root
<Directory /var/www/html>
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>

# Default charset
AddDefaultCharset UTF-8
